# Generated by Django 5.1.3 on 2026-05-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=50)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_title', models.CharField(default='🌸 Will you go on a date with me? 🌸', max_length=200)),
                ('ask_yes_button', models.CharField(default='YES 💗', max_length=50)),
                ('ask_no_button', models.CharField(default='no... 🙈', max_length=50)),
                ('ask_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('yay_title', models.CharField(default='WAIT YOU ACTUALLY SAID YES?? 😭', max_length=200)),
                ('yay_subtitle', models.CharField(default='I was so ready for you to say no 😂', max_length=200)),
                ('yay_button', models.CharField(default='okay okay! →', max_length=50)),
                ('yay_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('food_title', models.CharField(default='What are we feeling? 🍜✨', max_length=200)),
                ('food_button', models.CharField(default='this one! →', max_length=50)),
                ('schedule_title', models.CharField(default='So... when are you free?', max_length=200)),
                ('schedule_date_label', models.CharField(default='Pick a Day ✨', max_length=100)),
                ('schedule_time_label', models.CharField(default='Pick a Time ✨', max_length=100)),
                ('schedule_button', models.CharField(default='set the date! 💌', max_length=50)),
                ('final_title', models.CharField(default="glad you didn't say no. be ready by {time}, I'm coming to get you 🚗", help_text='Use {time} where the picked time should appear.', max_length=300)),
                ('final_note', models.TextField(default='P.S. normal people text. I made a website. during lunch. for you. no big deal.')),
                ('final_profile_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='site/videos/')),
                ('final_video_poster', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
