# Generated by Django 5.1.3 on 2026-05-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_askclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='her_name',
            field=models.CharField(blank=True, default='', help_text='Her name — used when the No button runs.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='no_runaway_messages',
            field=models.TextField(blank=True, default='please {name}...\n{name} wait 🥺\npretty please {name}?\nplease {name} say yes 💗', help_text='One message per line. Use {name} for her name — shown when she tries to click No.'),
        ),
    ]
