# Generated by Django 5.1.3 on 2026-05-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_sitecontent_her_name_sitecontent_no_runaway_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Full-page background photo (e.g. a picture of her).', null=True, upload_to='site/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='her_name',
            field=models.CharField(blank=True, default='', help_text='Her name — used in messages when the No button runs.', max_length=50),
        ),
    ]
