# Generated by Django 5.1.3 on 2026-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_sitecontent_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateproposal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='food_chosen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='said_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='said_yes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
